### ISSUE TITLE
MPLHEP Not installing

### ISSUE THREAD

**Issue by gabhijith** [scikit-hep/mplhep#16]
Hi,

MPLHEP is not getting instaled, I'm doing PIp install from Miniconda python v3.7.

Here are the logs

`Collecting mplhep
  Using cached https://files.pythonhosted.org/packages/9a/fc/ebc62df8eb5ba82ef6a8ea2ac654057f198595ffba259a0112525602898d/mplhep-0.0.17.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /cms/base/Miniconda/miniconda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_xj4eiz9/mplhep/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_xj4eiz9/mplhep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_xj4eiz9/mplhep/pip-egg-info
         cwd: /tmp/pip-install-_xj4eiz9/mplhep/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.39/el7-x86_64/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.39/el7-x86_64/usr/lib/python2.7/site-packages/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.39/el7-x86_64/usr/lib/python2.7/site-packages/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.39/el7-x86_64/usr/lib/python2.7/site-packages/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.39/el7-x86_64/usr/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.39/el7-x86_64/usr/lib/python2.7/site-packages/pkg_resources.py", line 1545, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by andrzejnovak** [comment]
@gabhijith I'm not able to replicate the issue
```
conda create -n testAbhijith python=3.7
conda activate testAbhijith
pip install mplhep
python
import mplhep as hep
```
works fine for me.

You might want to look at your paths i.e
```
which conda
which python
which pip
```

**Comment by gabhijith** [comment]
Oh thanks,

The issue I had was due to Open Science Grid setup script was interfering with mplhep for some reason. I fixed it.
