### ISSUE TITLE
Setting the style causes an error with Matplotlib 3.1.0

### ISSUE THREAD

**Issue by lmoureaux** [scikit-hep/mplhep#175]
I'm using `mplhep-0.1.29` from `pip` on LCG 98, which has Matplotlib 3.1.0. I get an exception when doing `plt.style.use(hep.style.ROOT)` as documented:
```
>>> import matplotlib as mpl
>>> mpl.__version__
'3.1.0'
>>> import mplhep as hep
>>> hep.__version__
'0.1.29'
>>> mpl.style.use(hep.style.ROOT)
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-slc6-gcc8-opt/lib/python3.6/site-packages/matplotlib/__init__.py", line 789, in __setitem__
    cval = self.validate[key](val)
KeyError: 'xaxis.labellocation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-slc6-gcc8-opt/lib/python3.6/site-packages/matplotlib/style/core.py", line 101, in use
    _apply_style(style)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-slc6-gcc8-opt/lib/python3.6/site-packages/matplotlib/style/core.py", line 62, in _apply_style
    mpl.rcParams.update(_remove_blacklisted_style_params(d, warn=warn))
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-6b228/x86_64-slc6-gcc8-opt/lib/python3.6/_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-slc6-gcc8-opt/lib/python3.6/site-packages/matplotlib/__init__.py", line 795, in __setitem__
    f"{key} is not a valid rc parameter (see rcParams.keys() for "
KeyError: 'xaxis.labellocation is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

```

**Comment by andrzejnovak** [comment]
:/ Yeah. Thanks for reporting, but this was expected. You could either install a --user version of matplotlib that will take precedence. Or alternatively, since the style is a dict you could do something like this:

```
cfg = hep.style.ROOT
del cfg['xaxis.labellocation']
del cfg['yaxis.labellocation']
plt.style.use(cfg)
```

AFAIK there's unfortunately not a way to keep both compatible at the same time.

**Comment by lmoureaux** [comment]
Thanks for the reply! I guess [the required Matplotlib version](https://github.com/scikit-hep/mplhep/blob/master/setup.py#L7) would need an update?

**Comment by andrzejnovak** [comment]
Hmm, is there an LCG stack with mpl 3.2? If not I would rather you can install a version with some features buggy rather than no version.

**Comment by lmoureaux** [comment]
Not a standard one, even `dev3` still has 3.1.0 (maybe I should ping them...). But `pip install --user` will install a newer version of the dependencies if the system version are too old.

**Comment by andrzejnovak** [comment]
@lmoureaux can you check with `mplhep==0.1.31` I added the version conditional removing above into the codebase and it looks like it should work. Though it's a bit of a dirty solution.

**Comment by lmoureaux** [comment]
This version does indeed work for me.

**Comment by andrzejnovak** [comment]
Great
