### ISSUE TITLE
No such file error on import: ".VERSION"

### ISSUE THREAD

**Issue by AndreasAlbert** [scikit-hep/mplhep#47]
The update from #45 seems to break my ability to import mplhep. I encounter this issue on both my laptop and github actions, with py 3.6 and 3.7

Error looks like this:

```
>>> import mplhep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/albert/code/virtualenv/bucoffea/lib/python3.7/site-packages/mplhep/__init__.py", line 39, in <module>
    with open(os.path.join(_base_dir, '.VERSION')) as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/albert/code/virtualenv/bucoffea/lib/python3.7/site-packages/.VERSION'
```

I figure the file is missing from the packaged version?

**Comment by andrzejnovak** [comment]
Sorry about that, #48 should fix it

**Comment by andrzejnovak** [comment]
Let me know if 0.0.35 fixes it.

**Comment by AndreasAlbert** [comment]
All better now! Thanks for the fast fix!
